server: 
  port: 9527                                      # 端口号
 
spring: 
  application:
    name: microservicecloud-zuul-gateway          # 微服务实例名
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway9527-zuul                 # 自定义服务名称信息
    prefer-ip-address: true                       # 访问路径可以显示IP
 
 
zuul:   
  prefix: /atguigu                                # 设置统一前缀
  #ignored-services: microservicecloud-dept       # 忽略真实微服务名
  ignored-services: "*"                           # 批量忽略真实微服务名
  routes: 
    mydept.serviceId: microservicecloud-dept      # 微服务名
    mydept.path: /mydept/**                       # 修改后的路径
 
info: 
  app.name: gateway-zuul-8527
  company.name: www.vek5.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  